version: 2

sources:
  - name: raw
    description: "Raw data ingested by Airflow from CSV"
    schema: public
    tables:
      - name: raw_customer_transactions
        description: "Unprocessed customer transactions (all columns TEXT)"
        columns:
          - name: transaction_id
            description: "Transaction ID (may have T prefix)"
          - name: customer_id
            description: "Customer ID (may be null, float format)"
          - name: transaction_date
            description: "Date (mixed formats: YYYY-MM-DD and DD-MM-YYYY)"
          - name: product_id
            description: "Product ID (may have P prefix)"
          - name: product_name
            description: "Product name"
          - name: quantity
            description: "Quantity (may be null)"
          - name: price
            description: "Price (may contain text such as 'Two Hundred')"
          - name: tax
            description: "Tax (may contain text such as 'Fifteen')"
